language: java
jdk:
  - oraclejdk8

after_failure:
  - cat TEST-*.txt

notifications:
  email:
    - christoph.boddy@gmail.com
    - ianopolous@gmail.com

sudo: required
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf